// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: physutil/demo/demo.proto

package demo

import (
	_ "github.com/aif-go/agproto-spec/phys"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 源：银行上游批量文件（GBK 定长）
type DemoSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        *string                `protobuf:"bytes,1,opt,name=cardNo,proto3,oneof" json:"cardNo,omitempty"`
	CustName      *string                `protobuf:"bytes,2,opt,name=custName,proto3,oneof" json:"custName,omitempty"`
	TxnAmt        *string                `protobuf:"bytes,3,opt,name=txnAmt,proto3,oneof" json:"txnAmt,omitempty"`
	BizDate       *string                `protobuf:"bytes,4,opt,name=bizDate,proto3,oneof" json:"bizDate,omitempty"`
	Filler        *string                `protobuf:"bytes,5,opt,name=filler,proto3,oneof" json:"filler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoSource) Reset() {
	*x = DemoSource{}
	mi := &file_physutil_demo_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoSource) ProtoMessage() {}

func (x *DemoSource) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_demo_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoSource.ProtoReflect.Descriptor instead.
func (*DemoSource) Descriptor() ([]byte, []int) {
	return file_physutil_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *DemoSource) GetCardNo() string {
	if x != nil && x.CardNo != nil {
		return *x.CardNo
	}
	return ""
}

func (x *DemoSource) GetCustName() string {
	if x != nil && x.CustName != nil {
		return *x.CustName
	}
	return ""
}

func (x *DemoSource) GetTxnAmt() string {
	if x != nil && x.TxnAmt != nil {
		return *x.TxnAmt
	}
	return ""
}

func (x *DemoSource) GetBizDate() string {
	if x != nil && x.BizDate != nil {
		return *x.BizDate
	}
	return ""
}

func (x *DemoSource) GetFiller() string {
	if x != nil && x.Filler != nil {
		return *x.Filler
	}
	return ""
}

// 标准：B2O 标准接口（UTF-8 分隔符）
type DemoStandard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        *string                `protobuf:"bytes,1,opt,name=cardNo,proto3,oneof" json:"cardNo,omitempty"`
	CustName      *string                `protobuf:"bytes,2,opt,name=custName,proto3,oneof" json:"custName,omitempty"`
	Amt           *string                `protobuf:"bytes,3,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	BizDate       *string                `protobuf:"bytes,4,opt,name=bizDate,proto3,oneof" json:"bizDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoStandard) Reset() {
	*x = DemoStandard{}
	mi := &file_physutil_demo_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoStandard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoStandard) ProtoMessage() {}

func (x *DemoStandard) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_demo_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoStandard.ProtoReflect.Descriptor instead.
func (*DemoStandard) Descriptor() ([]byte, []int) {
	return file_physutil_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *DemoStandard) GetCardNo() string {
	if x != nil && x.CardNo != nil {
		return *x.CardNo
	}
	return ""
}

func (x *DemoStandard) GetCustName() string {
	if x != nil && x.CustName != nil {
		return *x.CustName
	}
	return ""
}

func (x *DemoStandard) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *DemoStandard) GetBizDate() string {
	if x != nil && x.BizDate != nil {
		return *x.BizDate
	}
	return ""
}

var File_physutil_demo_demo_proto protoreflect.FileDescriptor

const file_physutil_demo_demo_proto_rawDesc = "" +
	"\n" +
	"\x18physutil/demo/demo.proto\x12\x04demo\x1a\x0fphys/phys.proto\"\xd0\x02\n" +
	"\n" +
	"DemoSource\x122\n" +
	"\x06cardNo\x18\x01 \x01(\tB\x15\x8a\xb5\x18\x11\x10\x13\x18\x01\"\x010:\x06cardNoH\x01H\x00R\x06cardNo\x88\x01\x01\x123\n" +
	"\bcustName\x18\x02 \x01(\tB\x12\x8a\xb5\x18\x0e\x10\x14:\bcustNameH\x02H\x01R\bcustName\x88\x01\x01\x123\n" +
	"\x06txnAmt\x18\x03 \x01(\tB\x16\x8a\xb5\x18\x12\x10\x0f\x18\x01\"\x0100\x02:\x03amtH\x03P\x02H\x02R\x06txnAmt\x88\x01\x01\x124\n" +
	"\abizDate\x18\x04 \x01(\tB\x15\x8a\xb5\x18\x11\x10\b:\abizDateH\x04P\x03`\x01H\x03R\abizDate\x88\x01\x01\x12'\n" +
	"\x06filler\x18\x05 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\x05@\x01H\x05H\x04R\x06filler\x88\x01\x01:\v\x8a\xb5\x18\a\b\x01*\x03GBKB\t\n" +
	"\a_cardNoB\v\n" +
	"\t_custNameB\t\n" +
	"\a_txnAmtB\n" +
	"\n" +
	"\b_bizDateB\t\n" +
	"\a_filler\"\xea\x01\n" +
	"\fDemoStandard\x12#\n" +
	"\x06cardNo\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x06cardNo\x88\x01\x01\x12'\n" +
	"\bcustName\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02H\x02H\x01R\bcustName\x88\x01\x01\x12#\n" +
	"\x03amt\x18\x03 \x01(\tB\f\x8a\xb5\x18\b0\x02H\x03P\x02X\x02H\x02R\x03amt\x88\x01\x01\x12)\n" +
	"\abizDate\x18\x04 \x01(\tB\n" +
	"\x8a\xb5\x18\x06H\x04P\x03`\x01H\x03R\abizDate\x88\x01\x01:\x10\x8a\xb5\x18\f\b\x02\x12\x01|*\x05UTF-8B\t\n" +
	"\a_cardNoB\v\n" +
	"\t_custNameB\x06\n" +
	"\x04_amtB\n" +
	"\n" +
	"\b_bizDateB.Z,github.com/aif-go/agproto-spec/physutil/demob\x06proto3"

var (
	file_physutil_demo_demo_proto_rawDescOnce sync.Once
	file_physutil_demo_demo_proto_rawDescData []byte
)

func file_physutil_demo_demo_proto_rawDescGZIP() []byte {
	file_physutil_demo_demo_proto_rawDescOnce.Do(func() {
		file_physutil_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_physutil_demo_demo_proto_rawDesc), len(file_physutil_demo_demo_proto_rawDesc)))
	})
	return file_physutil_demo_demo_proto_rawDescData
}

var file_physutil_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_physutil_demo_demo_proto_goTypes = []any{
	(*DemoSource)(nil),   // 0: demo.DemoSource
	(*DemoStandard)(nil), // 1: demo.DemoStandard
}
var file_physutil_demo_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_physutil_demo_demo_proto_init() }
func file_physutil_demo_demo_proto_init() {
	if File_physutil_demo_demo_proto != nil {
		return
	}
	file_physutil_demo_demo_proto_msgTypes[0].OneofWrappers = []any{}
	file_physutil_demo_demo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_physutil_demo_demo_proto_rawDesc), len(file_physutil_demo_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_physutil_demo_demo_proto_goTypes,
		DependencyIndexes: file_physutil_demo_demo_proto_depIdxs,
		MessageInfos:      file_physutil_demo_demo_proto_msgTypes,
	}.Build()
	File_physutil_demo_demo_proto = out.File
	file_physutil_demo_demo_proto_goTypes = nil
	file_physutil_demo_demo_proto_depIdxs = nil
}
