// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: phys/phys.proto

package phys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PadMode int32

const (
	PadMode_PAD_UNSPECIFIED PadMode = 0
	PadMode_PAD_LEFT        PadMode = 1
	PadMode_PAD_RIGHT       PadMode = 2
)

// Enum value maps for PadMode.
var (
	PadMode_name = map[int32]string{
		0: "PAD_UNSPECIFIED",
		1: "PAD_LEFT",
		2: "PAD_RIGHT",
	}
	PadMode_value = map[string]int32{
		"PAD_UNSPECIFIED": 0,
		"PAD_LEFT":        1,
		"PAD_RIGHT":       2,
	}
)

func (x PadMode) Enum() *PadMode {
	p := new(PadMode)
	*p = x
	return p
}

func (x PadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[0].Descriptor()
}

func (PadMode) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[0]
}

func (x PadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PadMode.Descriptor instead.
func (PadMode) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{0}
}

type SourceFormat int32

const (
	SourceFormat_FORMAT_UNSPECIFIED SourceFormat = 0
	SourceFormat_FORMAT_FIXED       SourceFormat = 1
	SourceFormat_FORMAT_DELIMITED   SourceFormat = 2
)

// Enum value maps for SourceFormat.
var (
	SourceFormat_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_FIXED",
		2: "FORMAT_DELIMITED",
	}
	SourceFormat_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_FIXED":       1,
		"FORMAT_DELIMITED":   2,
	}
)

func (x SourceFormat) Enum() *SourceFormat {
	p := new(SourceFormat)
	*p = x
	return p
}

func (x SourceFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[1].Descriptor()
}

func (SourceFormat) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[1]
}

func (x SourceFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceFormat.Descriptor instead.
func (SourceFormat) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{1}
}

// 字段类型语义声明（缺省 TYPE_UNSPECIFIED = 跟随 proto 字段类型）
type FieldType int32

const (
	FieldType_TYPE_UNSPECIFIED FieldType = 0
	FieldType_TYPE_STRING      FieldType = 1
	FieldType_TYPE_DECIMAL     FieldType = 2 // 必须带 precision
	FieldType_TYPE_DATE        FieldType = 3 // 必须带 date_pattern
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STRING",
		2: "TYPE_DECIMAL",
		3: "TYPE_DATE",
	}
	FieldType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STRING":      1,
		"TYPE_DECIMAL":     2,
		"TYPE_DATE":        3,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[2].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[2]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{2}
}

// DECIMAL 存储模式（缺省 SCALED）
type DecimalMode int32

const (
	DecimalMode_DECIMAL_MODE_UNSPECIFIED DecimalMode = 0 // 缺省 = SCALED
	DecimalMode_DECIMAL_MODE_SCALED      DecimalMode = 1 // 整数缩放："12345" + precision 2 → 123.45
	DecimalMode_DECIMAL_MODE_EXPLICIT    DecimalMode = 2 // 显式小数点："123.45" → 123.45
)

// Enum value maps for DecimalMode.
var (
	DecimalMode_name = map[int32]string{
		0: "DECIMAL_MODE_UNSPECIFIED",
		1: "DECIMAL_MODE_SCALED",
		2: "DECIMAL_MODE_EXPLICIT",
	}
	DecimalMode_value = map[string]int32{
		"DECIMAL_MODE_UNSPECIFIED": 0,
		"DECIMAL_MODE_SCALED":      1,
		"DECIMAL_MODE_EXPLICIT":    2,
	}
)

func (x DecimalMode) Enum() *DecimalMode {
	p := new(DecimalMode)
	*p = x
	return p
}

func (x DecimalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecimalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[3].Descriptor()
}

func (DecimalMode) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[3]
}

func (x DecimalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecimalMode.Descriptor instead.
func (DecimalMode) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{3}
}

// DATE 格式（预定义枚举，宽度 = 字符数）
type DatePattern int32

const (
	DatePattern_DATE_PATTERN_UNSPECIFIED    DatePattern = 0
	DatePattern_DATE_PATTERN_YYYYMMDD       DatePattern = 1 // 8 位
	DatePattern_DATE_PATTERN_HHMMSS         DatePattern = 2 // 6 位
	DatePattern_DATE_PATTERN_YYYYMMDDHHMMSS DatePattern = 3 // 14 位
)

// Enum value maps for DatePattern.
var (
	DatePattern_name = map[int32]string{
		0: "DATE_PATTERN_UNSPECIFIED",
		1: "DATE_PATTERN_YYYYMMDD",
		2: "DATE_PATTERN_HHMMSS",
		3: "DATE_PATTERN_YYYYMMDDHHMMSS",
	}
	DatePattern_value = map[string]int32{
		"DATE_PATTERN_UNSPECIFIED":    0,
		"DATE_PATTERN_YYYYMMDD":       1,
		"DATE_PATTERN_HHMMSS":         2,
		"DATE_PATTERN_YYYYMMDDHHMMSS": 3,
	}
)

func (x DatePattern) Enum() *DatePattern {
	p := new(DatePattern)
	*p = x
	return p
}

func (x DatePattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatePattern) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[4].Descriptor()
}

func (DatePattern) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[4]
}

func (x DatePattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatePattern.Descriptor instead.
func (DatePattern) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{4}
}

type FieldLayout struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset *int32                 `protobuf:"varint,1,opt,name=offset,proto3,oneof" json:"offset,omitempty"`             // 可选覆盖：字节偏移（高级场景，跳过冗余区域）；缺省按 index 推算
	Length *int32                 `protobuf:"varint,2,opt,name=length,proto3,oneof" json:"length,omitempty"`             // 定长：字节宽度（index 定位时必填）
	Pad    *PadMode               `protobuf:"varint,3,opt,name=pad,proto3,enum=phys.PadMode,oneof" json:"pad,omitempty"` // 对齐模式（缺省 PAD_UNSPECIFIED）
	Fill   *string                `protobuf:"bytes,4,opt,name=fill,proto3,oneof" json:"fill,omitempty"`                  // 填充字符（缺省空格）
	// field 5 已删除（原 format 死字段，字段号不再复用）
	Precision     *int32       `protobuf:"varint,6,opt,name=precision,proto3,oneof" json:"precision,omitempty"`                                               // TYPE_DECIMAL：小数位 scale
	Target        *string      `protobuf:"bytes,7,opt,name=target,proto3,oneof" json:"target,omitempty"`                                                      // Map：目标字段名
	Skip          *bool        `protobuf:"varint,8,opt,name=skip,proto3,oneof" json:"skip,omitempty"`                                                         // Map：跳过（不进映射）
	Index         *int32       `protobuf:"varint,9,opt,name=index,proto3,oneof" json:"index,omitempty"`                                                       // 字段序号：定长=第几段 / 分隔符=第几列（1-based，缺省=声明顺序）
	Type          *FieldType   `protobuf:"varint,10,opt,name=type,proto3,enum=phys.FieldType,oneof" json:"type,omitempty"`                                    // 类型语义声明（缺省跟随 proto 字段类型）
	DecimalMode   *DecimalMode `protobuf:"varint,11,opt,name=decimal_mode,json=decimalMode,proto3,enum=phys.DecimalMode,oneof" json:"decimal_mode,omitempty"` // TYPE_DECIMAL：存储模式（缺省 SCALED）
	DatePattern   *DatePattern `protobuf:"varint,12,opt,name=date_pattern,json=datePattern,proto3,enum=phys.DatePattern,oneof" json:"date_pattern,omitempty"` // TYPE_DATE：日期格式枚举
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldLayout) Reset() {
	*x = FieldLayout{}
	mi := &file_phys_phys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldLayout) ProtoMessage() {}

func (x *FieldLayout) ProtoReflect() protoreflect.Message {
	mi := &file_phys_phys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldLayout.ProtoReflect.Descriptor instead.
func (*FieldLayout) Descriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{0}
}

func (x *FieldLayout) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *FieldLayout) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *FieldLayout) GetPad() PadMode {
	if x != nil && x.Pad != nil {
		return *x.Pad
	}
	return PadMode_PAD_UNSPECIFIED
}

func (x *FieldLayout) GetFill() string {
	if x != nil && x.Fill != nil {
		return *x.Fill
	}
	return ""
}

func (x *FieldLayout) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *FieldLayout) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *FieldLayout) GetSkip() bool {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return false
}

func (x *FieldLayout) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *FieldLayout) GetType() FieldType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return FieldType_TYPE_UNSPECIFIED
}

func (x *FieldLayout) GetDecimalMode() DecimalMode {
	if x != nil && x.DecimalMode != nil {
		return *x.DecimalMode
	}
	return DecimalMode_DECIMAL_MODE_UNSPECIFIED
}

func (x *FieldLayout) GetDatePattern() DatePattern {
	if x != nil && x.DatePattern != nil {
		return *x.DatePattern
	}
	return DatePattern_DATE_PATTERN_UNSPECIFIED
}

type FileFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *SourceFormat          `protobuf:"varint,1,opt,name=format,proto3,enum=phys.SourceFormat,oneof" json:"format,omitempty"`            // FIXED / DELIMITED
	Delimiter     *string                `protobuf:"bytes,2,opt,name=delimiter,proto3,oneof" json:"delimiter,omitempty"`                              // 分隔符格式的分隔符
	HeaderLines   *int32                 `protobuf:"varint,3,opt,name=header_lines,json=headerLines,proto3,oneof" json:"header_lines,omitempty"`      // 跳过表头行数
	TrailerLines  *int32                 `protobuf:"varint,4,opt,name=trailer_lines,json=trailerLines,proto3,oneof" json:"trailer_lines,omitempty"`   // 跳过表尾行数
	Encoding      *string                `protobuf:"bytes,5,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`                                // 文件编码（如 "GBK"/"UTF-8"）
	LineSeparator *string                `protobuf:"bytes,6,opt,name=line_separator,json=lineSeparator,proto3,oneof" json:"line_separator,omitempty"` // 行分隔符（缺省 \n）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFormat) Reset() {
	*x = FileFormat{}
	mi := &file_phys_phys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFormat) ProtoMessage() {}

func (x *FileFormat) ProtoReflect() protoreflect.Message {
	mi := &file_phys_phys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFormat.ProtoReflect.Descriptor instead.
func (*FileFormat) Descriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{1}
}

func (x *FileFormat) GetFormat() SourceFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return SourceFormat_FORMAT_UNSPECIFIED
}

func (x *FileFormat) GetDelimiter() string {
	if x != nil && x.Delimiter != nil {
		return *x.Delimiter
	}
	return ""
}

func (x *FileFormat) GetHeaderLines() int32 {
	if x != nil && x.HeaderLines != nil {
		return *x.HeaderLines
	}
	return 0
}

func (x *FileFormat) GetTrailerLines() int32 {
	if x != nil && x.TrailerLines != nil {
		return *x.TrailerLines
	}
	return 0
}

func (x *FileFormat) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *FileFormat) GetLineSeparator() string {
	if x != nil && x.LineSeparator != nil {
		return *x.LineSeparator
	}
	return ""
}

var file_phys_phys_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldLayout)(nil),
		Field:         50001,
		Name:          "phys.layout",
		Tag:           "bytes,50001,opt,name=layout",
		Filename:      "phys/phys.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*FileFormat)(nil),
		Field:         50001,
		Name:          "phys.file",
		Tag:           "bytes,50001,opt,name=file",
		Filename:      "phys/phys.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional phys.FieldLayout layout = 50001;
	E_Layout = &file_phys_phys_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional phys.FileFormat file = 50001;
	E_File = &file_phys_phys_proto_extTypes[1]
)

var File_phys_phys_proto protoreflect.FileDescriptor

const file_phys_phys_proto_rawDesc = "" +
	"\n" +
	"\x0fphys/phys.proto\x12\x04phys\x1a google/protobuf/descriptor.proto\"\x98\x04\n" +
	"\vFieldLayout\x12\x1b\n" +
	"\x06offset\x18\x01 \x01(\x05H\x00R\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\x02 \x01(\x05H\x01R\x06length\x88\x01\x01\x12$\n" +
	"\x03pad\x18\x03 \x01(\x0e2\r.phys.PadModeH\x02R\x03pad\x88\x01\x01\x12\x17\n" +
	"\x04fill\x18\x04 \x01(\tH\x03R\x04fill\x88\x01\x01\x12!\n" +
	"\tprecision\x18\x06 \x01(\x05H\x04R\tprecision\x88\x01\x01\x12\x1b\n" +
	"\x06target\x18\a \x01(\tH\x05R\x06target\x88\x01\x01\x12\x17\n" +
	"\x04skip\x18\b \x01(\bH\x06R\x04skip\x88\x01\x01\x12\x19\n" +
	"\x05index\x18\t \x01(\x05H\aR\x05index\x88\x01\x01\x12(\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x0f.phys.FieldTypeH\bR\x04type\x88\x01\x01\x129\n" +
	"\fdecimal_mode\x18\v \x01(\x0e2\x11.phys.DecimalModeH\tR\vdecimalMode\x88\x01\x01\x129\n" +
	"\fdate_pattern\x18\f \x01(\x0e2\x11.phys.DatePatternH\n" +
	"R\vdatePattern\x88\x01\x01B\t\n" +
	"\a_offsetB\t\n" +
	"\a_lengthB\x06\n" +
	"\x04_padB\a\n" +
	"\x05_fillB\f\n" +
	"\n" +
	"_precisionB\t\n" +
	"\a_targetB\a\n" +
	"\x05_skipB\b\n" +
	"\x06_indexB\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_decimal_modeB\x0f\n" +
	"\r_date_pattern\"\xdb\x02\n" +
	"\n" +
	"FileFormat\x12/\n" +
	"\x06format\x18\x01 \x01(\x0e2\x12.phys.SourceFormatH\x00R\x06format\x88\x01\x01\x12!\n" +
	"\tdelimiter\x18\x02 \x01(\tH\x01R\tdelimiter\x88\x01\x01\x12&\n" +
	"\fheader_lines\x18\x03 \x01(\x05H\x02R\vheaderLines\x88\x01\x01\x12(\n" +
	"\rtrailer_lines\x18\x04 \x01(\x05H\x03R\ftrailerLines\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\x05 \x01(\tH\x04R\bencoding\x88\x01\x01\x12*\n" +
	"\x0eline_separator\x18\x06 \x01(\tH\x05R\rlineSeparator\x88\x01\x01B\t\n" +
	"\a_formatB\f\n" +
	"\n" +
	"_delimiterB\x0f\n" +
	"\r_header_linesB\x10\n" +
	"\x0e_trailer_linesB\v\n" +
	"\t_encodingB\x11\n" +
	"\x0f_line_separator*;\n" +
	"\aPadMode\x12\x13\n" +
	"\x0fPAD_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPAD_LEFT\x10\x01\x12\r\n" +
	"\tPAD_RIGHT\x10\x02*N\n" +
	"\fSourceFormat\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFORMAT_FIXED\x10\x01\x12\x14\n" +
	"\x10FORMAT_DELIMITED\x10\x02*S\n" +
	"\tFieldType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_STRING\x10\x01\x12\x10\n" +
	"\fTYPE_DECIMAL\x10\x02\x12\r\n" +
	"\tTYPE_DATE\x10\x03*_\n" +
	"\vDecimalMode\x12\x1c\n" +
	"\x18DECIMAL_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DECIMAL_MODE_SCALED\x10\x01\x12\x19\n" +
	"\x15DECIMAL_MODE_EXPLICIT\x10\x02*\x80\x01\n" +
	"\vDatePattern\x12\x1c\n" +
	"\x18DATE_PATTERN_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DATE_PATTERN_YYYYMMDD\x10\x01\x12\x17\n" +
	"\x13DATE_PATTERN_HHMMSS\x10\x02\x12\x1f\n" +
	"\x1bDATE_PATTERN_YYYYMMDDHHMMSS\x10\x03:M\n" +
	"\x06layout\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x11.phys.FieldLayoutR\x06layout\x88\x01\x01:J\n" +
	"\x04file\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x10.phys.FileFormatR\x04file\x88\x01\x01B%Z#github.com/aif-go/agproto-spec/physb\x06proto3"

var (
	file_phys_phys_proto_rawDescOnce sync.Once
	file_phys_phys_proto_rawDescData []byte
)

func file_phys_phys_proto_rawDescGZIP() []byte {
	file_phys_phys_proto_rawDescOnce.Do(func() {
		file_phys_phys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phys_phys_proto_rawDesc), len(file_phys_phys_proto_rawDesc)))
	})
	return file_phys_phys_proto_rawDescData
}

var file_phys_phys_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_phys_phys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_phys_phys_proto_goTypes = []any{
	(PadMode)(0),                        // 0: phys.PadMode
	(SourceFormat)(0),                   // 1: phys.SourceFormat
	(FieldType)(0),                      // 2: phys.FieldType
	(DecimalMode)(0),                    // 3: phys.DecimalMode
	(DatePattern)(0),                    // 4: phys.DatePattern
	(*FieldLayout)(nil),                 // 5: phys.FieldLayout
	(*FileFormat)(nil),                  // 6: phys.FileFormat
	(*descriptorpb.FieldOptions)(nil),   // 7: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 8: google.protobuf.MessageOptions
}
var file_phys_phys_proto_depIdxs = []int32{
	0, // 0: phys.FieldLayout.pad:type_name -> phys.PadMode
	2, // 1: phys.FieldLayout.type:type_name -> phys.FieldType
	3, // 2: phys.FieldLayout.decimal_mode:type_name -> phys.DecimalMode
	4, // 3: phys.FieldLayout.date_pattern:type_name -> phys.DatePattern
	1, // 4: phys.FileFormat.format:type_name -> phys.SourceFormat
	7, // 5: phys.layout:extendee -> google.protobuf.FieldOptions
	8, // 6: phys.file:extendee -> google.protobuf.MessageOptions
	5, // 7: phys.layout:type_name -> phys.FieldLayout
	6, // 8: phys.file:type_name -> phys.FileFormat
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	7, // [7:9] is the sub-list for extension type_name
	5, // [5:7] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_phys_phys_proto_init() }
func file_phys_phys_proto_init() {
	if File_phys_phys_proto != nil {
		return
	}
	file_phys_phys_proto_msgTypes[0].OneofWrappers = []any{}
	file_phys_phys_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phys_phys_proto_rawDesc), len(file_phys_phys_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_phys_phys_proto_goTypes,
		DependencyIndexes: file_phys_phys_proto_depIdxs,
		EnumInfos:         file_phys_phys_proto_enumTypes,
		MessageInfos:      file_phys_phys_proto_msgTypes,
		ExtensionInfos:    file_phys_phys_proto_extTypes,
	}.Build()
	File_phys_phys_proto = out.File
	file_phys_phys_proto_goTypes = nil
	file_phys_phys_proto_depIdxs = nil
}
