// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: phys/phys.proto

package phys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PadMode int32

const (
	PadMode_PAD_UNSPECIFIED PadMode = 0
	PadMode_PAD_LEFT        PadMode = 1
	PadMode_PAD_RIGHT       PadMode = 2
)

// Enum value maps for PadMode.
var (
	PadMode_name = map[int32]string{
		0: "PAD_UNSPECIFIED",
		1: "PAD_LEFT",
		2: "PAD_RIGHT",
	}
	PadMode_value = map[string]int32{
		"PAD_UNSPECIFIED": 0,
		"PAD_LEFT":        1,
		"PAD_RIGHT":       2,
	}
)

func (x PadMode) Enum() *PadMode {
	p := new(PadMode)
	*p = x
	return p
}

func (x PadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[0].Descriptor()
}

func (PadMode) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[0]
}

func (x PadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PadMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PadMode(num)
	return nil
}

// Deprecated: Use PadMode.Descriptor instead.
func (PadMode) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{0}
}

type SourceFormat int32

const (
	SourceFormat_FORMAT_UNSPECIFIED SourceFormat = 0
	SourceFormat_FORMAT_FIXED       SourceFormat = 1
	SourceFormat_FORMAT_DELIMITED   SourceFormat = 2
)

// Enum value maps for SourceFormat.
var (
	SourceFormat_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_FIXED",
		2: "FORMAT_DELIMITED",
	}
	SourceFormat_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_FIXED":       1,
		"FORMAT_DELIMITED":   2,
	}
)

func (x SourceFormat) Enum() *SourceFormat {
	p := new(SourceFormat)
	*p = x
	return p
}

func (x SourceFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_phys_phys_proto_enumTypes[1].Descriptor()
}

func (SourceFormat) Type() protoreflect.EnumType {
	return &file_phys_phys_proto_enumTypes[1]
}

func (x SourceFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SourceFormat) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SourceFormat(num)
	return nil
}

// Deprecated: Use SourceFormat.Descriptor instead.
func (SourceFormat) EnumDescriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{1}
}

type FieldLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        *int32                 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length        *int32                 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Pad           *PadMode               `protobuf:"varint,3,opt,name=pad,enum=phys.PadMode" json:"pad,omitempty"`
	Fill          *string                `protobuf:"bytes,4,opt,name=fill" json:"fill,omitempty"`
	Format        *string                `protobuf:"bytes,5,opt,name=format" json:"format,omitempty"`
	Precision     *int32                 `protobuf:"varint,6,opt,name=precision" json:"precision,omitempty"`
	Target        *string                `protobuf:"bytes,7,opt,name=target" json:"target,omitempty"`
	Skip          *bool                  `protobuf:"varint,8,opt,name=skip" json:"skip,omitempty"`
	Index         *int32                 `protobuf:"varint,9,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldLayout) Reset() {
	*x = FieldLayout{}
	mi := &file_phys_phys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldLayout) ProtoMessage() {}

func (x *FieldLayout) ProtoReflect() protoreflect.Message {
	mi := &file_phys_phys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldLayout.ProtoReflect.Descriptor instead.
func (*FieldLayout) Descriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{0}
}

func (x *FieldLayout) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *FieldLayout) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *FieldLayout) GetPad() PadMode {
	if x != nil && x.Pad != nil {
		return *x.Pad
	}
	return PadMode_PAD_UNSPECIFIED
}

func (x *FieldLayout) GetFill() string {
	if x != nil && x.Fill != nil {
		return *x.Fill
	}
	return ""
}

func (x *FieldLayout) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *FieldLayout) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *FieldLayout) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *FieldLayout) GetSkip() bool {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return false
}

func (x *FieldLayout) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type SourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *SourceFormat          `protobuf:"varint,1,opt,name=format,enum=phys.SourceFormat" json:"format,omitempty"`
	Delimiter     *string                `protobuf:"bytes,2,opt,name=delimiter" json:"delimiter,omitempty"`
	SkipHeader    *int32                 `protobuf:"varint,3,opt,name=skip_header,json=skipHeader" json:"skip_header,omitempty"`
	SkipTrailer   *int32                 `protobuf:"varint,4,opt,name=skip_trailer,json=skipTrailer" json:"skip_trailer,omitempty"`
	FileEncoding  *string                `protobuf:"bytes,5,opt,name=file_encoding,json=fileEncoding" json:"file_encoding,omitempty"`
	LineSeparator *string                `protobuf:"bytes,6,opt,name=line_separator,json=lineSeparator" json:"line_separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_phys_phys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_phys_phys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{1}
}

func (x *SourceConfig) GetFormat() SourceFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return SourceFormat_FORMAT_UNSPECIFIED
}

func (x *SourceConfig) GetDelimiter() string {
	if x != nil && x.Delimiter != nil {
		return *x.Delimiter
	}
	return ""
}

func (x *SourceConfig) GetSkipHeader() int32 {
	if x != nil && x.SkipHeader != nil {
		return *x.SkipHeader
	}
	return 0
}

func (x *SourceConfig) GetSkipTrailer() int32 {
	if x != nil && x.SkipTrailer != nil {
		return *x.SkipTrailer
	}
	return 0
}

func (x *SourceConfig) GetFileEncoding() string {
	if x != nil && x.FileEncoding != nil {
		return *x.FileEncoding
	}
	return ""
}

func (x *SourceConfig) GetLineSeparator() string {
	if x != nil && x.LineSeparator != nil {
		return *x.LineSeparator
	}
	return ""
}

type OutputConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *bool                  `protobuf:"varint,1,opt,name=header" json:"header,omitempty"`
	Trailer       *bool                  `protobuf:"varint,2,opt,name=trailer" json:"trailer,omitempty"`
	Encoding      *string                `protobuf:"bytes,3,opt,name=encoding" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputConfig) Reset() {
	*x = OutputConfig{}
	mi := &file_phys_phys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputConfig) ProtoMessage() {}

func (x *OutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_phys_phys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputConfig.ProtoReflect.Descriptor instead.
func (*OutputConfig) Descriptor() ([]byte, []int) {
	return file_phys_phys_proto_rawDescGZIP(), []int{2}
}

func (x *OutputConfig) GetHeader() bool {
	if x != nil && x.Header != nil {
		return *x.Header
	}
	return false
}

func (x *OutputConfig) GetTrailer() bool {
	if x != nil && x.Trailer != nil {
		return *x.Trailer
	}
	return false
}

func (x *OutputConfig) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

var file_phys_phys_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldLayout)(nil),
		Field:         50001,
		Name:          "phys.layout",
		Tag:           "bytes,50001,opt,name=layout",
		Filename:      "phys/phys.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*SourceConfig)(nil),
		Field:         50001,
		Name:          "phys.source",
		Tag:           "bytes,50001,opt,name=source",
		Filename:      "phys/phys.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*OutputConfig)(nil),
		Field:         50002,
		Name:          "phys.output",
		Tag:           "bytes,50002,opt,name=output",
		Filename:      "phys/phys.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional phys.FieldLayout layout = 50001;
	E_Layout = &file_phys_phys_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional phys.SourceConfig source = 50001;
	E_Source = &file_phys_phys_proto_extTypes[1]
	// optional phys.OutputConfig output = 50002;
	E_Output = &file_phys_phys_proto_extTypes[2]
)

var File_phys_phys_proto protoreflect.FileDescriptor

const file_phys_phys_proto_rawDesc = "" +
	"\n" +
	"\x0fphys/phys.proto\x12\x04phys\x1a google/protobuf/descriptor.proto\"\xea\x01\n" +
	"\vFieldLayout\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x1f\n" +
	"\x03pad\x18\x03 \x01(\x0e2\r.phys.PadModeR\x03pad\x12\x12\n" +
	"\x04fill\x18\x04 \x01(\tR\x04fill\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1c\n" +
	"\tprecision\x18\x06 \x01(\x05R\tprecision\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x12\x12\n" +
	"\x04skip\x18\b \x01(\bR\x04skip\x12\x14\n" +
	"\x05index\x18\t \x01(\x05R\x05index\"\xe8\x01\n" +
	"\fSourceConfig\x12*\n" +
	"\x06format\x18\x01 \x01(\x0e2\x12.phys.SourceFormatR\x06format\x12\x1c\n" +
	"\tdelimiter\x18\x02 \x01(\tR\tdelimiter\x12\x1f\n" +
	"\vskip_header\x18\x03 \x01(\x05R\n" +
	"skipHeader\x12!\n" +
	"\fskip_trailer\x18\x04 \x01(\x05R\vskipTrailer\x12#\n" +
	"\rfile_encoding\x18\x05 \x01(\tR\ffileEncoding\x12%\n" +
	"\x0eline_separator\x18\x06 \x01(\tR\rlineSeparator\"\\\n" +
	"\fOutputConfig\x12\x16\n" +
	"\x06header\x18\x01 \x01(\bR\x06header\x12\x18\n" +
	"\atrailer\x18\x02 \x01(\bR\atrailer\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\tR\bencoding*;\n" +
	"\aPadMode\x12\x13\n" +
	"\x0fPAD_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPAD_LEFT\x10\x01\x12\r\n" +
	"\tPAD_RIGHT\x10\x02*N\n" +
	"\fSourceFormat\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFORMAT_FIXED\x10\x01\x12\x14\n" +
	"\x10FORMAT_DELIMITED\x10\x02:J\n" +
	"\x06layout\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x11.phys.FieldLayoutR\x06layout:M\n" +
	"\x06source\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x12.phys.SourceConfigR\x06source:M\n" +
	"\x06output\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\v2\x12.phys.OutputConfigR\x06outputB%Z#github.com/aif-go/agproto-spec/phys"

var (
	file_phys_phys_proto_rawDescOnce sync.Once
	file_phys_phys_proto_rawDescData []byte
)

func file_phys_phys_proto_rawDescGZIP() []byte {
	file_phys_phys_proto_rawDescOnce.Do(func() {
		file_phys_phys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phys_phys_proto_rawDesc), len(file_phys_phys_proto_rawDesc)))
	})
	return file_phys_phys_proto_rawDescData
}

var file_phys_phys_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_phys_phys_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_phys_phys_proto_goTypes = []any{
	(PadMode)(0),                        // 0: phys.PadMode
	(SourceFormat)(0),                   // 1: phys.SourceFormat
	(*FieldLayout)(nil),                 // 2: phys.FieldLayout
	(*SourceConfig)(nil),                // 3: phys.SourceConfig
	(*OutputConfig)(nil),                // 4: phys.OutputConfig
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 6: google.protobuf.MessageOptions
}
var file_phys_phys_proto_depIdxs = []int32{
	0, // 0: phys.FieldLayout.pad:type_name -> phys.PadMode
	1, // 1: phys.SourceConfig.format:type_name -> phys.SourceFormat
	5, // 2: phys.layout:extendee -> google.protobuf.FieldOptions
	6, // 3: phys.source:extendee -> google.protobuf.MessageOptions
	6, // 4: phys.output:extendee -> google.protobuf.MessageOptions
	2, // 5: phys.layout:type_name -> phys.FieldLayout
	3, // 6: phys.source:type_name -> phys.SourceConfig
	4, // 7: phys.output:type_name -> phys.OutputConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	2, // [2:5] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_phys_phys_proto_init() }
func file_phys_phys_proto_init() {
	if File_phys_phys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phys_phys_proto_rawDesc), len(file_phys_phys_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_phys_phys_proto_goTypes,
		DependencyIndexes: file_phys_phys_proto_depIdxs,
		EnumInfos:         file_phys_phys_proto_enumTypes,
		MessageInfos:      file_phys_phys_proto_msgTypes,
		ExtensionInfos:    file_phys_phys_proto_extTypes,
	}.Build()
	File_phys_phys_proto = out.File
	file_phys_phys_proto_goTypes = nil
	file_phys_phys_proto_depIdxs = nil
}
