// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: physutil/internal/testdata/test.proto

package testdata

import (
	_ "github.com/aif-go/agproto-spec/phys"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum kind 构建期拒绝
type TestKind int32

const (
	TestKind_TEST_KIND_ZERO TestKind = 0
	TestKind_TEST_KIND_ONE  TestKind = 1
)

// Enum value maps for TestKind.
var (
	TestKind_name = map[int32]string{
		0: "TEST_KIND_ZERO",
		1: "TEST_KIND_ONE",
	}
	TestKind_value = map[string]int32{
		"TEST_KIND_ZERO": 0,
		"TEST_KIND_ONE":  1,
	}
)

func (x TestKind) Enum() *TestKind {
	p := new(TestKind)
	*p = x
	return p
}

func (x TestKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestKind) Descriptor() protoreflect.EnumDescriptor {
	return file_physutil_internal_testdata_test_proto_enumTypes[0].Descriptor()
}

func (TestKind) Type() protoreflect.EnumType {
	return &file_physutil_internal_testdata_test_proto_enumTypes[0]
}

func (x TestKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestKind.Descriptor instead.
func (TestKind) EnumDescriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{0}
}

type ValidFixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Card          *string                `protobuf:"bytes,2,opt,name=card,proto3,oneof" json:"card,omitempty"`
	Age           *int64                 `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Amt           *string                `protobuf:"bytes,4,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	Rate          *string                `protobuf:"bytes,5,opt,name=rate,proto3,oneof" json:"rate,omitempty"`
	BizDt         *string                `protobuf:"bytes,6,opt,name=bizDt,proto3,oneof" json:"bizDt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidFixed) Reset() {
	*x = ValidFixed{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidFixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidFixed) ProtoMessage() {}

func (x *ValidFixed) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidFixed.ProtoReflect.Descriptor instead.
func (*ValidFixed) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{0}
}

func (x *ValidFixed) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ValidFixed) GetCard() string {
	if x != nil && x.Card != nil {
		return *x.Card
	}
	return ""
}

func (x *ValidFixed) GetAge() int64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *ValidFixed) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *ValidFixed) GetRate() string {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return ""
}

func (x *ValidFixed) GetBizDt() string {
	if x != nil && x.BizDt != nil {
		return *x.BizDt
	}
	return ""
}

type ValidFixedOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidFixedOffset) Reset() {
	*x = ValidFixedOffset{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidFixedOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidFixedOffset) ProtoMessage() {}

func (x *ValidFixedOffset) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidFixedOffset.ProtoReflect.Descriptor instead.
func (*ValidFixedOffset) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{1}
}

func (x *ValidFixedOffset) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *ValidFixedOffset) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type ValidDelimited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	C             *int64                 `protobuf:"varint,3,opt,name=c,proto3,oneof" json:"c,omitempty"`
	Amt           *string                `protobuf:"bytes,4,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidDelimited) Reset() {
	*x = ValidDelimited{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidDelimited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidDelimited) ProtoMessage() {}

func (x *ValidDelimited) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidDelimited.ProtoReflect.Descriptor instead.
func (*ValidDelimited) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{2}
}

func (x *ValidDelimited) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *ValidDelimited) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

func (x *ValidDelimited) GetC() int64 {
	if x != nil && x.C != nil {
		return *x.C
	}
	return 0
}

func (x *ValidDelimited) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

type Overlap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overlap) Reset() {
	*x = Overlap{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overlap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overlap) ProtoMessage() {}

func (x *Overlap) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overlap.ProtoReflect.Descriptor instead.
func (*Overlap) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{3}
}

func (x *Overlap) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *Overlap) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type DupIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DupIndex) Reset() {
	*x = DupIndex{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DupIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DupIndex) ProtoMessage() {}

func (x *DupIndex) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DupIndex.ProtoReflect.Descriptor instead.
func (*DupIndex) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{4}
}

func (x *DupIndex) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *DupIndex) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type NoLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoLength) Reset() {
	*x = NoLength{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoLength) ProtoMessage() {}

func (x *NoLength) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoLength.ProtoReflect.Descriptor instead.
func (*NoLength) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{5}
}

func (x *NoLength) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type DelimitedWithOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelimitedWithOffset) Reset() {
	*x = DelimitedWithOffset{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelimitedWithOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelimitedWithOffset) ProtoMessage() {}

func (x *DelimitedWithOffset) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelimitedWithOffset.ProtoReflect.Descriptor instead.
func (*DelimitedWithOffset) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{6}
}

func (x *DelimitedWithOffset) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type DecimalNoPrecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalNoPrecision) Reset() {
	*x = DecimalNoPrecision{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalNoPrecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalNoPrecision) ProtoMessage() {}

func (x *DecimalNoPrecision) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalNoPrecision.ProtoReflect.Descriptor instead.
func (*DecimalNoPrecision) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{7}
}

func (x *DecimalNoPrecision) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type StringWithPrecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringWithPrecision) Reset() {
	*x = StringWithPrecision{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringWithPrecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringWithPrecision) ProtoMessage() {}

func (x *StringWithPrecision) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringWithPrecision.ProtoReflect.Descriptor instead.
func (*StringWithPrecision) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{8}
}

func (x *StringWithPrecision) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type DateNoPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateNoPattern) Reset() {
	*x = DateNoPattern{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateNoPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateNoPattern) ProtoMessage() {}

func (x *DateNoPattern) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateNoPattern.ProtoReflect.Descriptor instead.
func (*DateNoPattern) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{9}
}

func (x *DateNoPattern) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type DateWidthMismatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateWidthMismatch) Reset() {
	*x = DateWidthMismatch{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateWidthMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateWidthMismatch) ProtoMessage() {}

func (x *DateWidthMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateWidthMismatch.ProtoReflect.Descriptor instead.
func (*DateWidthMismatch) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{10}
}

func (x *DateWidthMismatch) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type BoolField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *bool                  `protobuf:"varint,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolField) Reset() {
	*x = BoolField{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolField) ProtoMessage() {}

func (x *BoolField) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolField.ProtoReflect.Descriptor instead.
func (*BoolField) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{11}
}

func (x *BoolField) GetA() bool {
	if x != nil && x.A != nil {
		return *x.A
	}
	return false
}

type IntTypeMismatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *int64                 `protobuf:"varint,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntTypeMismatch) Reset() {
	*x = IntTypeMismatch{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntTypeMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntTypeMismatch) ProtoMessage() {}

func (x *IntTypeMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntTypeMismatch.ProtoReflect.Descriptor instead.
func (*IntTypeMismatch) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{12}
}

func (x *IntTypeMismatch) GetA() int64 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

type ZeroLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroLength) Reset() {
	*x = ZeroLength{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroLength) ProtoMessage() {}

func (x *ZeroLength) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroLength.ProtoReflect.Descriptor instead.
func (*ZeroLength) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{13}
}

func (x *ZeroLength) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type ZeroIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroIndex) Reset() {
	*x = ZeroIndex{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroIndex) ProtoMessage() {}

func (x *ZeroIndex) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroIndex.ProtoReflect.Descriptor instead.
func (*ZeroIndex) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{14}
}

func (x *ZeroIndex) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type NegativeOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegativeOffset) Reset() {
	*x = NegativeOffset{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegativeOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegativeOffset) ProtoMessage() {}

func (x *NegativeOffset) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegativeOffset.ProtoReflect.Descriptor instead.
func (*NegativeOffset) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{15}
}

func (x *NegativeOffset) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *NegativeOffset) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type ExplicitDecimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amt           *string                `protobuf:"bytes,1,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplicitDecimal) Reset() {
	*x = ExplicitDecimal{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitDecimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitDecimal) ProtoMessage() {}

func (x *ExplicitDecimal) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitDecimal.ProtoReflect.Descriptor instead.
func (*ExplicitDecimal) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{16}
}

func (x *ExplicitDecimal) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

type DecimalOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amt           *string                `protobuf:"bytes,1,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalOnly) Reset() {
	*x = DecimalOnly{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalOnly) ProtoMessage() {}

func (x *DecimalOnly) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalOnly.ProtoReflect.Descriptor instead.
func (*DecimalOnly) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{17}
}

func (x *DecimalOnly) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

type DecimalExplicitOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amt           *string                `protobuf:"bytes,1,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalExplicitOnly) Reset() {
	*x = DecimalExplicitOnly{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalExplicitOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalExplicitOnly) ProtoMessage() {}

func (x *DecimalExplicitOnly) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalExplicitOnly.ProtoReflect.Descriptor instead.
func (*DecimalExplicitOnly) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{18}
}

func (x *DecimalExplicitOnly) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

type ValidDelimitedTab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidDelimitedTab) Reset() {
	*x = ValidDelimitedTab{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidDelimitedTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidDelimitedTab) ProtoMessage() {}

func (x *ValidDelimitedTab) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidDelimitedTab.ProtoReflect.Descriptor instead.
func (*ValidDelimitedTab) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{19}
}

func (x *ValidDelimitedTab) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *ValidDelimitedTab) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type ValidDelimitedMulti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidDelimitedMulti) Reset() {
	*x = ValidDelimitedMulti{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidDelimitedMulti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidDelimitedMulti) ProtoMessage() {}

func (x *ValidDelimitedMulti) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidDelimitedMulti.ProtoReflect.Descriptor instead.
func (*ValidDelimitedMulti) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{20}
}

func (x *ValidDelimitedMulti) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *ValidDelimitedMulti) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

type ValidFixedSkip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	B             *string                `protobuf:"bytes,2,opt,name=b,proto3,oneof" json:"b,omitempty"`
	C             *string                `protobuf:"bytes,3,opt,name=c,proto3,oneof" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidFixedSkip) Reset() {
	*x = ValidFixedSkip{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidFixedSkip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidFixedSkip) ProtoMessage() {}

func (x *ValidFixedSkip) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidFixedSkip.ProtoReflect.Descriptor instead.
func (*ValidFixedSkip) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{21}
}

func (x *ValidFixedSkip) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

func (x *ValidFixedSkip) GetB() string {
	if x != nil && x.B != nil {
		return *x.B
	}
	return ""
}

func (x *ValidFixedSkip) GetC() string {
	if x != nil && x.C != nil {
		return *x.C
	}
	return ""
}

type EmptyDelimiter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyDelimiter) Reset() {
	*x = EmptyDelimiter{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyDelimiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyDelimiter) ProtoMessage() {}

func (x *EmptyDelimiter) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyDelimiter.ProtoReflect.Descriptor instead.
func (*EmptyDelimiter) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{22}
}

func (x *EmptyDelimiter) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type EnumField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             *TestKind              `protobuf:"varint,1,opt,name=k,proto3,enum=physutil.testdata.TestKind,oneof" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumField) Reset() {
	*x = EnumField{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumField) ProtoMessage() {}

func (x *EnumField) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumField.ProtoReflect.Descriptor instead.
func (*EnumField) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{23}
}

func (x *EnumField) GetK() TestKind {
	if x != nil && x.K != nil {
		return *x.K
	}
	return TestKind_TEST_KIND_ZERO
}

type Int32Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             *int32                 `protobuf:"varint,1,opt,name=n,proto3,oneof" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Field) Reset() {
	*x = Int32Field{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Field) ProtoMessage() {}

func (x *Int32Field) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Field.ProtoReflect.Descriptor instead.
func (*Int32Field) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{24}
}

func (x *Int32Field) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

type NoFileOpt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoFileOpt) Reset() {
	*x = NoFileOpt{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoFileOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFileOpt) ProtoMessage() {}

func (x *NoFileOpt) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFileOpt.ProtoReflect.Descriptor instead.
func (*NoFileOpt) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{25}
}

func (x *NoFileOpt) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type WithHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithHeader) Reset() {
	*x = WithHeader{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithHeader) ProtoMessage() {}

func (x *WithHeader) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithHeader.ProtoReflect.Descriptor instead.
func (*WithHeader) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{26}
}

func (x *WithHeader) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type FillMultiByte struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillMultiByte) Reset() {
	*x = FillMultiByte{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillMultiByte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillMultiByte) ProtoMessage() {}

func (x *FillMultiByte) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillMultiByte.ProtoReflect.Descriptor instead.
func (*FillMultiByte) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{27}
}

func (x *FillMultiByte) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type HugeLength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HugeLength) Reset() {
	*x = HugeLength{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HugeLength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugeLength) ProtoMessage() {}

func (x *HugeLength) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugeLength.ProtoReflect.Descriptor instead.
func (*HugeLength) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{28}
}

func (x *HugeLength) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

// 裸 scalar（非 optional）：无 presence，值类型字段
type BareField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareField) Reset() {
	*x = BareField{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareField) ProtoMessage() {}

func (x *BareField) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BareField.ProtoReflect.Descriptor instead.
func (*BareField) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{29}
}

func (x *BareField) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *BareField) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type EncFixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Card          *string                `protobuf:"bytes,2,opt,name=card,proto3,oneof" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncFixed) Reset() {
	*x = EncFixed{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncFixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncFixed) ProtoMessage() {}

func (x *EncFixed) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncFixed.ProtoReflect.Descriptor instead.
func (*EncFixed) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{30}
}

func (x *EncFixed) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EncFixed) GetCard() string {
	if x != nil && x.Card != nil {
		return *x.Card
	}
	return ""
}

type EncDelimited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Card          *string                `protobuf:"bytes,2,opt,name=card,proto3,oneof" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncDelimited) Reset() {
	*x = EncDelimited{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncDelimited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncDelimited) ProtoMessage() {}

func (x *EncDelimited) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncDelimited.ProtoReflect.Descriptor instead.
func (*EncDelimited) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{31}
}

func (x *EncDelimited) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EncDelimited) GetCard() string {
	if x != nil && x.Card != nil {
		return *x.Card
	}
	return ""
}

type EncUnknown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *string                `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncUnknown) Reset() {
	*x = EncUnknown{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncUnknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncUnknown) ProtoMessage() {}

func (x *EncUnknown) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncUnknown.ProtoReflect.Descriptor instead.
func (*EncUnknown) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{32}
}

func (x *EncUnknown) GetA() string {
	if x != nil && x.A != nil {
		return *x.A
	}
	return ""
}

type MapSrc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Amt           *string                `protobuf:"bytes,2,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	Junk          *string                `protobuf:"bytes,3,opt,name=junk,proto3,oneof" json:"junk,omitempty"`
	Qty           *int64                 `protobuf:"varint,4,opt,name=qty,proto3,oneof" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSrc) Reset() {
	*x = MapSrc{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSrc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSrc) ProtoMessage() {}

func (x *MapSrc) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSrc.ProtoReflect.Descriptor instead.
func (*MapSrc) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{33}
}

func (x *MapSrc) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *MapSrc) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *MapSrc) GetJunk() string {
	if x != nil && x.Junk != nil {
		return *x.Junk
	}
	return ""
}

func (x *MapSrc) GetQty() int64 {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return 0
}

type MapDst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Amt           *string                `protobuf:"bytes,2,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	Qty           *string                `protobuf:"bytes,3,opt,name=qty,proto3,oneof" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDst) Reset() {
	*x = MapDst{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDst) ProtoMessage() {}

func (x *MapDst) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDst.ProtoReflect.Descriptor instead.
func (*MapDst) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{34}
}

func (x *MapDst) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *MapDst) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *MapDst) GetQty() string {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return ""
}

type MapDstScale4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Amt           *string                `protobuf:"bytes,1,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	Qty           *string                `protobuf:"bytes,3,opt,name=qty,proto3,oneof" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDstScale4) Reset() {
	*x = MapDstScale4{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDstScale4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDstScale4) ProtoMessage() {}

func (x *MapDstScale4) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDstScale4.ProtoReflect.Descriptor instead.
func (*MapDstScale4) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{35}
}

func (x *MapDstScale4) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *MapDstScale4) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *MapDstScale4) GetQty() string {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return ""
}

type MapDstLossy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Amt           *string                `protobuf:"bytes,1,opt,name=amt,proto3,oneof" json:"amt,omitempty"`
	Qty           *string                `protobuf:"bytes,3,opt,name=qty,proto3,oneof" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDstLossy) Reset() {
	*x = MapDstLossy{}
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDstLossy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDstLossy) ProtoMessage() {}

func (x *MapDstLossy) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDstLossy.ProtoReflect.Descriptor instead.
func (*MapDstLossy) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test_proto_rawDescGZIP(), []int{36}
}

func (x *MapDstLossy) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *MapDstLossy) GetAmt() string {
	if x != nil && x.Amt != nil {
		return *x.Amt
	}
	return ""
}

func (x *MapDstLossy) GetQty() string {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return ""
}

var File_physutil_internal_testdata_test_proto protoreflect.FileDescriptor

const file_physutil_internal_testdata_test_proto_rawDesc = "" +
	"\n" +
	"%physutil/internal/testdata/test.proto\x12\x11physutil.testdata\x1a\x0fphys/phys.proto\"\xb9\x02\n" +
	"\n" +
	"ValidFixed\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\n" +
	"H\x01H\x00R\x04name\x88\x01\x01\x12&\n" +
	"\x04card\x18\x02 \x01(\tB\r\x8a\xb5\x18\t\x10\x13\x18\x01\"\x010H\x02H\x01R\x04card\x88\x01\x01\x12$\n" +
	"\x03age\x18\x03 \x01(\x03B\r\x8a\xb5\x18\t\x10\x04\x18\x01\"\x010H\x03H\x02R\x03age\x88\x01\x01\x12(\n" +
	"\x03amt\x18\x04 \x01(\tB\x11\x8a\xb5\x18\r\x10\x0f\x18\x01\"\x0100\x02H\x04P\x02H\x03R\x03amt\x88\x01\x01\x12*\n" +
	"\x04rate\x18\x05 \x01(\tB\x11\x8a\xb5\x18\r\x10\b\x18\x01\"\x0100\x06H\x05P\x02H\x04R\x04rate\x88\x01\x01\x12'\n" +
	"\x05bizDt\x18\x06 \x01(\tB\f\x8a\xb5\x18\b\x10\bH\x06P\x03`\x01H\x05R\x05bizDt\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_cardB\x06\n" +
	"\x04_ageB\x06\n" +
	"\x04_amtB\a\n" +
	"\x05_rateB\b\n" +
	"\x06_bizDt\"b\n" +
	"\x10ValidFixedOffset\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\n" +
	"H\x01H\x00R\x01a\x88\x01\x01\x12\x1d\n" +
	"\x01b\x18\x02 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\bd\x10\n" +
	"H\x02H\x01R\x01b\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"\xa9\x01\n" +
	"\x0eValidDelimited\x12\x19\n" +
	"\x01a\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x01a\x88\x01\x01\x12\x19\n" +
	"\x01b\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02H\x03H\x01R\x01b\x88\x01\x01\x12\x19\n" +
	"\x01c\x18\x03 \x01(\x03B\x06\x8a\xb5\x18\x02H\x04H\x02R\x01c\x88\x01\x01\x12!\n" +
	"\x03amt\x18\x04 \x01(\tB\n" +
	"\x8a\xb5\x18\x060\x02H\x05P\x02H\x03R\x03amt\x88\x01\x01:\t\x8a\xb5\x18\x05\b\x02\x12\x01|B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_bB\x04\n" +
	"\x02_cB\x06\n" +
	"\x04_amt\"Y\n" +
	"\aOverlap\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\n" +
	"H\x01H\x00R\x01a\x88\x01\x01\x12\x1d\n" +
	"\x01b\x18\x02 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b\x05\x10\x05H\x02H\x01R\x01b\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"X\n" +
	"\bDupIndex\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x02H\x00R\x01a\x88\x01\x01\x12\x1b\n" +
	"\x01b\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x02H\x01R\x01b\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"3\n" +
	"\bNoLength\x12\x19\n" +
	"\x01a\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"E\n" +
	"\x13DelimitedWithOffset\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b\x00\x10\x05H\x01H\x00R\x01a\x88\x01\x01:\t\x8a\xb5\x18\x05\b\x02\x12\x01|B\x04\n" +
	"\x02_a\"A\n" +
	"\x12DecimalNoPrecision\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\n" +
	"H\x01P\x02H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"B\n" +
	"\x13StringWithPrecision\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\n" +
	"0\x02H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"<\n" +
	"\rDateNoPattern\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\bH\x01P\x03H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"B\n" +
	"\x11DateWidthMismatch\x12\x1f\n" +
	"\x01a\x18\x01 \x01(\tB\f\x8a\xb5\x18\b\x10\n" +
	"H\x01P\x03`\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"6\n" +
	"\tBoolField\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\bB\b\x8a\xb5\x18\x04\x10\x01H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\">\n" +
	"\x0fIntTypeMismatch\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\x03B\n" +
	"\x8a\xb5\x18\x06\x10\x04H\x01P\x02H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"7\n" +
	"\n" +
	"ZeroLength\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x00H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"6\n" +
	"\tZeroIndex\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x00H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"i\n" +
	"\x0eNegativeOffset\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x01a\x88\x01\x01\x12&\n" +
	"\x01b\x18\x02 \x01(\tB\x13\x8a\xb5\x18\x0f\b\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x10\x05H\x02H\x01R\x01b\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"M\n" +
	"\x0fExplicitDecimal\x12*\n" +
	"\x03amt\x18\x01 \x01(\tB\x13\x8a\xb5\x18\x0f\x10\b\x18\x01\"\x0100\x02H\x01P\x02X\x02H\x00R\x03amt\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x06\n" +
	"\x04_amt\"G\n" +
	"\vDecimalOnly\x12(\n" +
	"\x03amt\x18\x01 \x01(\tB\x11\x8a\xb5\x18\r\x10\x0f\x18\x01\"\x0100\x02H\x01P\x02H\x00R\x03amt\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x06\n" +
	"\x04_amt\"Q\n" +
	"\x13DecimalExplicitOnly\x12*\n" +
	"\x03amt\x18\x01 \x01(\tB\x13\x8a\xb5\x18\x0f\x10\b\x18\x01\"\x0100\x02H\x01P\x02X\x02H\x00R\x03amt\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x06\n" +
	"\x04_amt\"`\n" +
	"\x11ValidDelimitedTab\x12\x19\n" +
	"\x01a\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x01a\x88\x01\x01\x12\x19\n" +
	"\x01b\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02H\x02H\x01R\x01b\x88\x01\x01:\t\x8a\xb5\x18\x05\b\x02\x12\x01\tB\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"c\n" +
	"\x13ValidDelimitedMulti\x12\x19\n" +
	"\x01a\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x01a\x88\x01\x01\x12\x19\n" +
	"\x01b\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02H\x02H\x01R\x01b\x88\x01\x01:\n" +
	"\x8a\xb5\x18\x06\b\x02\x12\x02||B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_b\"\x83\x01\n" +
	"\x0eValidFixedSkip\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x01a\x88\x01\x01\x12\x1d\n" +
	"\x01b\x18\x02 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\x05@\x01H\x02H\x01R\x01b\x88\x01\x01\x12\x1b\n" +
	"\x01c\x18\x03 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x03H\x02R\x01c\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_aB\x04\n" +
	"\x02_bB\x04\n" +
	"\x02_c\"9\n" +
	"\x0eEmptyDelimiter\x12\x19\n" +
	"\x01a\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x02B\x04\n" +
	"\x02_a\"S\n" +
	"\tEnumField\x128\n" +
	"\x01k\x18\x01 \x01(\x0e2\x1b.physutil.testdata.TestKindB\b\x8a\xb5\x18\x04\x10\x02H\x01H\x00R\x01k\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_k\"<\n" +
	"\n" +
	"Int32Field\x12 \n" +
	"\x01n\x18\x01 \x01(\x05B\r\x8a\xb5\x18\t\x10\x05\x18\x01\"\x010H\x01H\x00R\x01n\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_n\".\n" +
	"\tNoFileOpt\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x01a\x88\x01\x01B\x04\n" +
	"\x02_a\"D\n" +
	"\n" +
	"WithHeader\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x01a\x88\x01\x01:\x13\x8a\xb5\x18\x0f\b\x01\x18\x01 \x02*\x03GBK2\x02\r\n" +
	"B\x04\n" +
	"\x02_a\">\n" +
	"\rFillMultiByte\x12\x1f\n" +
	"\x01a\x18\x01 \x01(\tB\f\x8a\xb5\x18\b\x10\x05\"\x0200H\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\";\n" +
	"\n" +
	"HugeLength\x12\x1f\n" +
	"\x01a\x18\x01 \x01(\tB\f\x8a\xb5\x18\b\x10\x80\xa8ֹ\aH\x01H\x00R\x01a\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x04\n" +
	"\x02_a\"H\n" +
	"\tBareField\x12\x16\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01R\x01a\x12\x1b\n" +
	"\x01b\x18\x02 \x01(\x03B\r\x8a\xb5\x18\t\x10\x04\x18\x01\"\x010H\x02R\x01b:\x06\x8a\xb5\x18\x02\b\x01\"t\n" +
	"\bEncFixed\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x14H\x01H\x00R\x04name\x88\x01\x01\x12&\n" +
	"\x04card\x18\x02 \x01(\tB\r\x8a\xb5\x18\t\x10\x13\x18\x01\"\x010H\x02H\x01R\x04card\x88\x01\x01:\v\x8a\xb5\x18\a\b\x01*\x03GBKB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_card\"r\n" +
	"\fEncDelimited\x12\x1f\n" +
	"\x04name\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02H\x01H\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\x04card\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02H\x02H\x01R\x04card\x88\x01\x01:\x0e\x8a\xb5\x18\n" +
	"\b\x02\x12\x01|*\x03GBKB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_card\"?\n" +
	"\n" +
	"EncUnknown\x12\x1b\n" +
	"\x01a\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x01a\x88\x01\x01:\x0e\x8a\xb5\x18\n" +
	"\b\x01*\x06NOSUCHB\x04\n" +
	"\x02_a\"\xda\x01\n" +
	"\x06MapSrc\x12'\n" +
	"\x04code\x18\x01 \x01(\tB\x0e\x8a\xb5\x18\n" +
	"\x10\x05:\x04codeH\x01H\x00R\x04code\x88\x01\x01\x12-\n" +
	"\x03amt\x18\x02 \x01(\tB\x16\x8a\xb5\x18\x12\x10\x0f\x18\x01\"\x0100\x02:\x03amtH\x02P\x02H\x01R\x03amt\x88\x01\x01\x12#\n" +
	"\x04junk\x18\x03 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\x10\x05@\x01H\x03H\x02R\x04junk\x88\x01\x01\x12)\n" +
	"\x03qty\x18\x04 \x01(\x03B\x12\x8a\xb5\x18\x0e\x10\x04\x18\x01\"\x010:\x03qtyH\x04H\x03R\x03qty\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_amtB\a\n" +
	"\x05_junkB\x06\n" +
	"\x04_qty\"\x9c\x01\n" +
	"\x06MapDst\x12!\n" +
	"\x04code\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x01H\x00R\x04code\x88\x01\x01\x12(\n" +
	"\x03amt\x18\x02 \x01(\tB\x11\x8a\xb5\x18\r\x10\x0f\x18\x01\"\x0100\x02H\x02P\x02H\x01R\x03amt\x88\x01\x01\x12$\n" +
	"\x03qty\x18\x03 \x01(\tB\r\x8a\xb5\x18\t\x10\x04\x18\x01\"\x010H\x03H\x02R\x03qty\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_amtB\x06\n" +
	"\x04_qty\"\xa2\x01\n" +
	"\fMapDstScale4\x12!\n" +
	"\x04code\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x02H\x00R\x04code\x88\x01\x01\x12(\n" +
	"\x03amt\x18\x01 \x01(\tB\x11\x8a\xb5\x18\r\x10\x12\x18\x01\"\x0100\x04H\x01P\x02H\x01R\x03amt\x88\x01\x01\x12$\n" +
	"\x03qty\x18\x03 \x01(\tB\r\x8a\xb5\x18\t\x10\x04\x18\x01\"\x010H\x03H\x02R\x03qty\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_amtB\x06\n" +
	"\x04_qty\"\xa1\x01\n" +
	"\vMapDstLossy\x12!\n" +
	"\x04code\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\x10\x05H\x02H\x00R\x04code\x88\x01\x01\x12(\n" +
	"\x03amt\x18\x01 \x01(\tB\x11\x8a\xb5\x18\r\x10\x0e\x18\x01\"\x0100\x01H\x01P\x02H\x01R\x03amt\x88\x01\x01\x12$\n" +
	"\x03qty\x18\x03 \x01(\tB\r\x8a\xb5\x18\t\x10\x04\x18\x01\"\x010H\x03H\x02R\x03qty\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_amtB\x06\n" +
	"\x04_qty*1\n" +
	"\bTestKind\x12\x12\n" +
	"\x0eTEST_KIND_ZERO\x10\x00\x12\x11\n" +
	"\rTEST_KIND_ONE\x10\x01B;Z9github.com/aif-go/agproto-spec/physutil/internal/testdatab\x06proto3"

var (
	file_physutil_internal_testdata_test_proto_rawDescOnce sync.Once
	file_physutil_internal_testdata_test_proto_rawDescData []byte
)

func file_physutil_internal_testdata_test_proto_rawDescGZIP() []byte {
	file_physutil_internal_testdata_test_proto_rawDescOnce.Do(func() {
		file_physutil_internal_testdata_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_physutil_internal_testdata_test_proto_rawDesc), len(file_physutil_internal_testdata_test_proto_rawDesc)))
	})
	return file_physutil_internal_testdata_test_proto_rawDescData
}

var file_physutil_internal_testdata_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_physutil_internal_testdata_test_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_physutil_internal_testdata_test_proto_goTypes = []any{
	(TestKind)(0),               // 0: physutil.testdata.TestKind
	(*ValidFixed)(nil),          // 1: physutil.testdata.ValidFixed
	(*ValidFixedOffset)(nil),    // 2: physutil.testdata.ValidFixedOffset
	(*ValidDelimited)(nil),      // 3: physutil.testdata.ValidDelimited
	(*Overlap)(nil),             // 4: physutil.testdata.Overlap
	(*DupIndex)(nil),            // 5: physutil.testdata.DupIndex
	(*NoLength)(nil),            // 6: physutil.testdata.NoLength
	(*DelimitedWithOffset)(nil), // 7: physutil.testdata.DelimitedWithOffset
	(*DecimalNoPrecision)(nil),  // 8: physutil.testdata.DecimalNoPrecision
	(*StringWithPrecision)(nil), // 9: physutil.testdata.StringWithPrecision
	(*DateNoPattern)(nil),       // 10: physutil.testdata.DateNoPattern
	(*DateWidthMismatch)(nil),   // 11: physutil.testdata.DateWidthMismatch
	(*BoolField)(nil),           // 12: physutil.testdata.BoolField
	(*IntTypeMismatch)(nil),     // 13: physutil.testdata.IntTypeMismatch
	(*ZeroLength)(nil),          // 14: physutil.testdata.ZeroLength
	(*ZeroIndex)(nil),           // 15: physutil.testdata.ZeroIndex
	(*NegativeOffset)(nil),      // 16: physutil.testdata.NegativeOffset
	(*ExplicitDecimal)(nil),     // 17: physutil.testdata.ExplicitDecimal
	(*DecimalOnly)(nil),         // 18: physutil.testdata.DecimalOnly
	(*DecimalExplicitOnly)(nil), // 19: physutil.testdata.DecimalExplicitOnly
	(*ValidDelimitedTab)(nil),   // 20: physutil.testdata.ValidDelimitedTab
	(*ValidDelimitedMulti)(nil), // 21: physutil.testdata.ValidDelimitedMulti
	(*ValidFixedSkip)(nil),      // 22: physutil.testdata.ValidFixedSkip
	(*EmptyDelimiter)(nil),      // 23: physutil.testdata.EmptyDelimiter
	(*EnumField)(nil),           // 24: physutil.testdata.EnumField
	(*Int32Field)(nil),          // 25: physutil.testdata.Int32Field
	(*NoFileOpt)(nil),           // 26: physutil.testdata.NoFileOpt
	(*WithHeader)(nil),          // 27: physutil.testdata.WithHeader
	(*FillMultiByte)(nil),       // 28: physutil.testdata.FillMultiByte
	(*HugeLength)(nil),          // 29: physutil.testdata.HugeLength
	(*BareField)(nil),           // 30: physutil.testdata.BareField
	(*EncFixed)(nil),            // 31: physutil.testdata.EncFixed
	(*EncDelimited)(nil),        // 32: physutil.testdata.EncDelimited
	(*EncUnknown)(nil),          // 33: physutil.testdata.EncUnknown
	(*MapSrc)(nil),              // 34: physutil.testdata.MapSrc
	(*MapDst)(nil),              // 35: physutil.testdata.MapDst
	(*MapDstScale4)(nil),        // 36: physutil.testdata.MapDstScale4
	(*MapDstLossy)(nil),         // 37: physutil.testdata.MapDstLossy
}
var file_physutil_internal_testdata_test_proto_depIdxs = []int32{
	0, // 0: physutil.testdata.EnumField.k:type_name -> physutil.testdata.TestKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_physutil_internal_testdata_test_proto_init() }
func file_physutil_internal_testdata_test_proto_init() {
	if File_physutil_internal_testdata_test_proto != nil {
		return
	}
	file_physutil_internal_testdata_test_proto_msgTypes[0].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[1].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[2].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[3].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[4].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[5].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[6].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[7].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[8].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[9].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[10].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[11].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[12].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[13].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[14].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[15].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[16].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[17].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[18].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[19].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[20].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[21].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[22].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[23].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[24].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[25].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[26].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[27].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[28].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[30].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[31].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[32].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[33].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[34].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[35].OneofWrappers = []any{}
	file_physutil_internal_testdata_test_proto_msgTypes[36].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_physutil_internal_testdata_test_proto_rawDesc), len(file_physutil_internal_testdata_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_physutil_internal_testdata_test_proto_goTypes,
		DependencyIndexes: file_physutil_internal_testdata_test_proto_depIdxs,
		EnumInfos:         file_physutil_internal_testdata_test_proto_enumTypes,
		MessageInfos:      file_physutil_internal_testdata_test_proto_msgTypes,
	}.Build()
	File_physutil_internal_testdata_test_proto = out.File
	file_physutil_internal_testdata_test_proto_goTypes = nil
	file_physutil_internal_testdata_test_proto_depIdxs = nil
}
