// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: physutil/internal/testdata/test2.proto

package testdata

import (
	_ "github.com/aif-go/agproto-spec/phys"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// proto2 业务文件兼容性验证：跨语法使用 proto3 的 phys custom options
type Proto2Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Qty           *int64                 `protobuf:"varint,2,opt,name=qty" json:"qty,omitempty"`
	Date          *string                `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto2Msg) Reset() {
	*x = Proto2Msg{}
	mi := &file_physutil_internal_testdata_test2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2Msg) ProtoMessage() {}

func (x *Proto2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_physutil_internal_testdata_test2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2Msg.ProtoReflect.Descriptor instead.
func (*Proto2Msg) Descriptor() ([]byte, []int) {
	return file_physutil_internal_testdata_test2_proto_rawDescGZIP(), []int{0}
}

func (x *Proto2Msg) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Proto2Msg) GetQty() int64 {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return 0
}

func (x *Proto2Msg) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

var File_physutil_internal_testdata_test2_proto protoreflect.FileDescriptor

const file_physutil_internal_testdata_test2_proto_rawDesc = "" +
	"\n" +
	"&physutil/internal/testdata/test2.proto\x12\x11physutil.testdata\x1a\x0fphys/phys.proto\"t\n" +
	"\tProto2Msg\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\x10\n" +
	"H\x01R\x04name\x12\x1f\n" +
	"\x03qty\x18\x02 \x01(\x03B\r\x8a\xb5\x18\t\x10\x0f\x18\x01\"\x010H\x02R\x03qty\x12 \n" +
	"\x04date\x18\x03 \x01(\tB\f\x8a\xb5\x18\b\x10\bH\x03P\x03`\x01R\x04date:\x06\x8a\xb5\x18\x02\b\x01B;Z9github.com/aif-go/agproto-spec/physutil/internal/testdata"

var (
	file_physutil_internal_testdata_test2_proto_rawDescOnce sync.Once
	file_physutil_internal_testdata_test2_proto_rawDescData []byte
)

func file_physutil_internal_testdata_test2_proto_rawDescGZIP() []byte {
	file_physutil_internal_testdata_test2_proto_rawDescOnce.Do(func() {
		file_physutil_internal_testdata_test2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_physutil_internal_testdata_test2_proto_rawDesc), len(file_physutil_internal_testdata_test2_proto_rawDesc)))
	})
	return file_physutil_internal_testdata_test2_proto_rawDescData
}

var file_physutil_internal_testdata_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_physutil_internal_testdata_test2_proto_goTypes = []any{
	(*Proto2Msg)(nil), // 0: physutil.testdata.Proto2Msg
}
var file_physutil_internal_testdata_test2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_physutil_internal_testdata_test2_proto_init() }
func file_physutil_internal_testdata_test2_proto_init() {
	if File_physutil_internal_testdata_test2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_physutil_internal_testdata_test2_proto_rawDesc), len(file_physutil_internal_testdata_test2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_physutil_internal_testdata_test2_proto_goTypes,
		DependencyIndexes: file_physutil_internal_testdata_test2_proto_depIdxs,
		MessageInfos:      file_physutil_internal_testdata_test2_proto_msgTypes,
	}.Build()
	File_physutil_internal_testdata_test2_proto = out.File
	file_physutil_internal_testdata_test2_proto_goTypes = nil
	file_physutil_internal_testdata_test2_proto_depIdxs = nil
}
